
package Paquete;
import Clases.Unidemensional;
import Clases.Bidimensional;
import Clases.Maximizar;
import java.awt.Component;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    //Matriz unidem tratar de usar
    Unidemensional FunOb;
    Bidimensional Restric;
    Maximizar MSolu;

    
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        //TxtBloq.setEnabled(false);
            
        FunOb = new Unidemensional();
        Restric = new Bidimensional();
        MSolu = new Maximizar();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTipOp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JNvar = new javax.swing.JTextField();
        JNres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonReg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResul = new javax.swing.JTextPane();
        BResolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtBloq = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTipOp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de Operación :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("# Variables :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("# Restricciones :");

        JNvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNvarActionPerformed(evt);
            }
        });

        JNres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNresActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Solicitar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Maximizar");

        javax.swing.GroupLayout JTipOpLayout = new javax.swing.GroupLayout(JTipOp);
        JTipOp.setLayout(JTipOpLayout);
        JTipOpLayout.setHorizontalGroup(
            JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTipOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JNvar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JNres)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        JTipOpLayout.setVerticalGroup(
            JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTipOpLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JTipOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Modelo Programación Lineal");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Ingreso de Datos");

        BotonReg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonReg.setText("Salir");
        BotonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegActionPerformed(evt);
            }
        });

        txtResul.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jScrollPane2.setViewportView(txtResul);

        BResolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BResolver.setText("Resolver");
        BResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResolverActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Iteracciones");

        TxtBloq.setColumns(20);
        TxtBloq.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        TxtBloq.setRows(5);
        TxtBloq.setText("Aqui va el modelo matemático");
        jScrollPane1.setViewportView(TxtBloq);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Mostrar Resultados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTipOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonReg, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTipOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonReg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNvarActionPerformed

    private void JNresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ACA comienza
        int i,j, numv, numy;
        int nVar;// Numero de variablea
        int nRestr;// Num de restricciones
        String dato, texto1="", texto2="";
        float FOb[]= new float[10]; // almacen temporal
        
        nVar=Integer.valueOf(JNvar.getText());  //Nro de Variables -- Nro de columnas para la matriz
        nRestr=Integer.valueOf(JNres.getText());  //Nro de Restricciones -- Nro de filas -1 para la matriz
        
        //Class Array
        FunOb.setnfil(nVar);
        
        for(i=0;i<FunOb.getnfil();i++){
            numv=i+1;
            dato=JOptionPane.showInputDialog(MainFrame.this,"Ingrese datos " + numv+" :", "FUNCIÓN OBJETIVO",1);
            FOb[i]=Integer.valueOf(dato);
            dato="";
        }

        FunOb.setArr(FOb);//Asignar Array

        
        float Rest[][] = new float[10][10]; // almacen temporal
        // Matriz Restricciones
        Restric.setNcol(nVar);
        Restric.setNfila(nRestr);
        
        // Leer Restricciones
        for(j=0;j<nRestr;j++){
            numy=j+1;
            for(i=0;i<nVar+1;i++){
                numv=i+1;
                dato=JOptionPane.showInputDialog(MainFrame.this,"Ingrese datos " + numv +" :", "RESTRICCIÓN NRO. "+ numy,1);
                Rest[i][j]=Integer.valueOf(dato);
            }
        }
        Restric.setMa(Rest);
        
        
        // Mostrar Datos de Funcion Objetivo
       
        for(i=0;i<nVar;i++){

            numv=i+1;
            if(i!=nVar-1)
                texto1 = texto1 + FOb[i]+" X" +numv+ " + ";
            else
                texto1 = texto1 + FOb[i]+" X" +numv;
                
                       
        }
        //Mostrar Datos Restricciones
        for(j=0;j<nRestr;j++){
            numy=j+1;
            for(i=0;i<nVar+1;i++){
                numv=i+1;
                if(i<nVar-1)
                    texto2 = texto2 + Rest[i][j]+" X" +numv+ " + ";
                else if(i==nVar-1)
                    texto2 = texto2 + Rest[i][j]+" X" +numv;
                else
                    texto2 = texto2 + " <= " + Rest[i][j];
            }
            texto2 = texto2 + "\n";
        }
        for(i=0;i<nVar+1;i++){
            numv=i+1;
            if(i<nVar-1)
                texto2=texto2 + "X"+numv+ ", ";
            else if(i==nVar-1)
                texto2=texto2 + "X"+numv;
        }
        texto2 = texto2 + " >= " + 0+ "\n";
        
        TxtBloq.setText("Maximizar "+" Z" +"\n"+texto1 + "\n"+ "Sujeto a: \n"+texto2);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void BResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResolverActionPerformed
        ///Boton Resolver
        //Variables para correr Matriz
        float MSol[][] = new float[10][10];
        int i,j;
        // Dimensiones de matriz
        int nx=Restric.getNfila()+Restric.getNcol()+2, ny=Restric.getNfila()+1;
        
        
        int cuentar = 0,k;// Guarda donde quedo el registro 
        
        //Definimos la Fila 0 de Matriz Solucion
        j=0;
        MSol[0][j]=1;

        
        for (i=1;i<nx; i++) {
                    
                    if (FunOb.Arr[i-1]==0)
                        MSol[i][j]=0;
                    else
                        MSol[i][j]=-FunOb.Arr[i-1];
        }    
        //Definimos lo demas filas de Matriz Solucion  
        for(j=1;j<ny;j++){
            for (i=0;i<nx; i++) {
              
              if(i==0)
                    MSol[i][j]=0;
              else if(i<=Restric.getNcol()){
                  MSol[i][j]=Restric.Ma[i-1][j-1];
                  cuentar=i+1;
              }
              else if(i==nx-1)//Final de la fila de matriz
                  MSol[i][j]=Restric.Ma[Restric.getNcol()][j-1];
              
              for (k=cuentar; k < nx-1; k++) {
                         MSol[Restric.getNcol()+j][j]=1; 
                         //MSol[k][j]=0;
              }

            }
            }

        String textoPrueba= "Tabla Inicial \n" ;
        for(j=0;j<ny;j++){
            //textoPrueba=textoPrueba+"Fila "+j+"\n";
            for (i=0;i<nx; i++) {
                textoPrueba=textoPrueba+" "+ MSol[i][j] + " \t";
            }
            textoPrueba=textoPrueba+"\n";
            
        }
        
        MSolu.setMa(MSol);
        MSolu.setNcol(ny);
        MSolu.setNfila(nx);
        String nuevo ="";
        nuevo= MSolu.interaccion();
        textoPrueba=textoPrueba + nuevo;
        
        txtResul.setText(textoPrueba);

        
    }//GEN-LAST:event_BResolverActionPerformed

    
    private void BotonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonRegActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MostrarResultados ventana = new MostrarResultados();
        ventana.setVisible(true);
        String FinalResp= MSolu.MostraRespuesta();
        MostrarResultados.recibe.setText(FinalResp);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BResolver;
    private javax.swing.JButton BotonReg;
    private javax.swing.JTextField JNres;
    private javax.swing.JTextField JNvar;
    private javax.swing.JPanel JTipOp;
    private javax.swing.JTextArea TxtBloq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtResul;
    // End of variables declaration//GEN-END:variables
}
